name: Update Bundle

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-bundle:
    name: Build and commit dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.15
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build dist/ Directory
        run: pnpm run bundle

      - name: Commit updated bundle
        run: |
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add dist/
            git commit -m "chore: updated bundle"
            git push
          fi
